In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
from tqdm import tqdm

In [2]:
crime_df = pd.read_csv(r"C:\Users\assis\Downloads\filtered_crime_data.csv")
crime_df

C:\Users\assis\AppData\Local\Temp\ipykernel_33280\3779025263.py:1: DtypeWarning: Columns (0,10) have mixed types. Specify dtype option on import or set low_memory=False.
  crime_df = pd.read_csv(r"C:\Users\assis\Downloads\filtered_crime_data.csv")


Crime ID    Month  \
0                                                       NaN  2010-12   
1                                                       NaN  2010-12   
2                                                       NaN  2010-12   
3                                                       NaN  2010-12   
4                                                       NaN  2010-12   
...                                                     ...      ...   
13931521  cb73daf6b8479ac3c6f0393ccaed8ba09d656bc8ec7daf...  2024-01   
13931522  9bf4d909cbf838f713421c29a173c1fd1578393789ce37...  2024-01   
13931523  90ce6cc23afb135dcbc5eb17784b4d363375f9a076a2fd...  2024-01   
13931524  be7a1b283771dc0aefcef2b191a4f7e91403771e1d6065...  2024-01   
13931525  9006968a8e2fb5779017e7c6f1887ad21232b565cfe6df...  2024-01   

                          Reported by                 Falls within  Longitude  \
0         Metropolitan Police Service  Metropolitan Police Service   0.145949   
1         Metropolitan Police Service  Metropolitan Police Service   0.140192   
2         Metropolitan Police Service  Metropolitan Police Service   0.134947   
3         Metropolitan Police Service  Metropolitan Police Service   0.134947   
4         Metropolitan Police Service  Metropolitan Police Service   0.134947   
...                               ...                          ...        ...   
13931521  Metropolitan Police Service  Metropolitan Police Service  -0.133480   
13931522  Metropolitan Police Service  Metropolitan Police Service  -0.136284   
13931523  Metropolitan Police Service  Metropolitan Police Service  -0.136284   
13931524  Metropolitan Police Service  Metropolitan Police Service  -0.137230   
13931525  Metropolitan Police Service  Metropolitan Police Service  -0.136284   

           Latitude                            Location  LSOA code  \
0         51.593914         On or near Providence Place  E01000027   
1         51.582311              On or near Hatch Grove  E01000027   
2         51.588063               On or near Mead Grove  E01000027   
3         51.588063               On or near Mead Grove  E01000027   
4         51.588063               On or near Mead Grove  E01000027   
...             ...                                 ...        ...   
13931521  51.486807  On or near St George'S Square Mews  E01035722   
13931522  51.485152           On or near Petrol Station  E01035722   
13931523  51.485152           On or near Petrol Station  E01035722   
13931524  51.486309             On or near Parking Area  E01035722   
13931525  51.485152           On or near Petrol Station  E01035722   

                          LSOA name                    Crime type  \
0         Barking and Dagenham 001A         Anti-social behaviour   
1         Barking and Dagenham 001A         Anti-social behaviour   
2         Barking and Dagenham 001A         Anti-social behaviour   
3         Barking and Dagenham 001A         Anti-social behaviour   
4         Barking and Dagenham 001A         Anti-social behaviour   
...                             ...                           ...   
13931521           Westminster 024G     Criminal damage and arson   
13931522           Westminster 024G                   Other theft   
13931523           Westminster 024G         Theft from the person   
13931524           Westminster 024G  Violence and sexual offences   
13931525           Westminster 024G  Violence and sexual offences   

                                  Last outcome category  Context  \
0                                                   NaN      NaN   
1                                                   NaN      NaN   
2                                                   NaN      NaN   
3                                                   NaN      NaN   
4                                                   NaN      NaN   
...                                                 ...      ...   
13931521                            Under investigation      NaN   

In [3]:
imp_crime_df = crime_df[['Crime ID', 'Month', 'Crime type', 'Borough']]
imp_crime_df

Crime ID    Month  \
0                                                       NaN  2010-12   
1                                                       NaN  2010-12   
2                                                       NaN  2010-12   
3                                                       NaN  2010-12   
4                                                       NaN  2010-12   
...                                                     ...      ...   
13931521  cb73daf6b8479ac3c6f0393ccaed8ba09d656bc8ec7daf...  2024-01   
13931522  9bf4d909cbf838f713421c29a173c1fd1578393789ce37...  2024-01   
13931523  90ce6cc23afb135dcbc5eb17784b4d363375f9a076a2fd...  2024-01   
13931524  be7a1b283771dc0aefcef2b191a4f7e91403771e1d6065...  2024-01   
13931525  9006968a8e2fb5779017e7c6f1887ad21232b565cfe6df...  2024-01   

                            Crime type               Borough  
0                Anti-social behaviour  Barking and Dagenham  
1                Anti-social behaviour  Barking and Dagenham  
2                Anti-social behaviour  Barking and Dagenham  
3                Anti-social behaviour  Barking and Dagenham  
4                Anti-social behaviour  Barking and Dagenham  
...                                ...                   ...  
13931521     Criminal damage and arson           Westminster  
13931522                   Other theft           Westminster  
13931523         Theft from the person           Westminster  
13931524  Violence and sexual offences           Westminster  
13931525  Violence and sexual offences           Westminster  

[13931526 rows x 4 columns]

In [5]:
pivot_df = imp_crime_df.pivot_table(index=['Month', 'Borough'], 
                                    columns='Crime type', 
                                    aggfunc='size', 
                                    fill_value=0).reset_index()

pivot_df

Crime type    Month               Borough  Anti-social behaviour  \
0           2010-12  Barking and Dagenham                    837   
1           2010-12                Barnet                   1078   
2           2010-12                Bexley                    670   
3           2010-12                 Brent                   1280   
4           2010-12               Bromley                   1056   
...             ...                   ...                    ...   
5051        2024-01                Sutton                    219   
5052        2024-01         Tower Hamlets                    745   
5053        2024-01        Waltham Forest                    557   
5054        2024-01            Wandsworth                    530   
5055        2024-01           Westminster                    919   

Crime type  Bicycle theft  Burglary  Criminal damage and arson  Drugs  \
0                       0       149                          0      0   
1                       0       372                          0      0   
2                       0       151                          0      0   
3                       0       308                          0      0   
4                       0       279                          0      0   
...                   ...       ...                        ...    ...   
5051                    6        62                        134     32   
5052                   73       241                        160    111   
5053                   28       124                        111    104   
5054                   53       188                        163     79   
5055                   73       282                        182    172   

Crime type  Other crime  Other theft  Possession of weapons  \
0                   527            0                      0   
1                   848            0                      0   
2                   418            0                      0   
3                   878            0                      0   
4                   643            0                      0   
...                 ...          ...                    ...   
5051                 13          102                      7   
5052                 19          345                     15   
5053                 14          259                     18   
5054                 25          265                      9   
5055                 23         1810                     23   

Crime type  Public disorder and weapons  Public order  Robbery  Shoplifting  \
0                                     0             0       59            0   
1                                     0             0       58            0   
2                                     0             0       29            0   
3                                     0             0      136            0   
4                                     0             0       54            0   
...                                 ...           ...      ...          ...   
5051                                  0            77       25           93   
5052                                  0           178      109          172   
5053                                  0            92       71          126   
5054                                  0           148      102          155   
5055                                  0           276      317          479   

Crime type  Theft from the person  Vehicle crime  \
0                               0            189   
1                               0            275   
2                               0            108   
3                               0            240   
4                               0            245   
...                           ...            ...   
5051                           27            155   
5052                          231            269   
5053                          127            243   
5054                           67            305   
5055                        

In [16]:
month_data = [
    {'Month_Number': 49, 'Month_Year': 'Apr/15', 'MONTH': '49 (Apr 2015)'},
    {'Month_Number': 50, 'Month_Year': 'May/15', 'MONTH': '50 (May 2015)'},
    {'Month_Number': 51, 'Month_Year': 'Jun/15', 'MONTH': '51 (Jun 2015)'},
]

import calendar
from datetime import datetime

start_date = datetime(2010, 12, 1)
end_date = datetime(2024, 1, 1)
current_date = start_date

while current_date <= end_date:
    month_year = current_date.strftime('%b/%y')
    month_number = (current_date.year - 2015) * 12 + current_date.month + 45
    month_name = calendar.month_name[current_date.month]
    month_data.append({
        'Month_Number': month_number,
        'Month_Year': month_year,
        'MONTH': f'{month_number} ({month_name} {current_date.year})'
    })
    next_month = current_date.month % 12 + 1
    next_year = current_date.year + (current_date.month // 12)
    current_date = datetime(next_year, next_month, 1)

month_df = pd.DataFrame(month_data)

month_df

Month_Number Month_Year                 MONTH
0              49     Apr/15         49 (Apr 2015)
1              50     May/15         50 (May 2015)
2              51     Jun/15         51 (Jun 2015)
3              -3     Dec/10    -3 (December 2010)
4              -2     Jan/11     -2 (January 2011)
..            ...        ...                   ...
156           150     Sep/23  150 (September 2023)
157           151     Oct/23    151 (October 2023)
158           152     Nov/23   152 (November 2023)
159           153     Dec/23   153 (December 2023)
160           154     Jan/24    154 (January 2024)

[161 rows x 3 columns]

In [17]:
merged_df = pd.merge(pivot_df, month_df[['Month_Number', 'Month_Year']], on='Month_Year', how='left')
merged_df

Month_Year               Borough  Anti-social behaviour  Bicycle theft  \
0        Dec/10  Barking and Dagenham                    837              0   
1        Dec/10                Barnet                   1078              0   
2        Dec/10                Bexley                    670              0   
3        Dec/10                 Brent                   1280              0   
4        Dec/10               Bromley                   1056              0   
...         ...                   ...                    ...            ...   
5147     Jan/24                Sutton                    219              6   
5148     Jan/24         Tower Hamlets                    745             73   
5149     Jan/24        Waltham Forest                    557             28   
5150     Jan/24            Wandsworth                    530             53   
5151     Jan/24           Westminster                    919             73   

      Burglary  Criminal damage and arson  Drugs  Other crime  Other theft  \
0          149                          0      0          527            0   
1          372                          0      0          848            0   
2          151                          0      0          418            0   
3          308                          0      0          878            0   
4          279                          0      0          643            0   
...        ...                        ...    ...          ...          ...   
5147        62                        134     32           13          102   
5148       241                        160    111           19          345   
5149       124                        111    104           14          259   
5150       188                        163     79           25          265   
5151       282                        182    172           23         1810   

      Possession of weapons  Public disorder and weapons  Public order  \
0                         0                            0             0   
1                         0                            0             0   
2                         0                            0             0   
3                         0                            0             0   
4                         0                            0             0   
...                     ...                          ...           ...   
5147                      7                            0            77   
5148                     15                            0           178   
5149                     18                            0            92   
5150                      9                            0           148   
5151                     23                            0           276   

      Robbery  Shoplifting  Theft from the person  Vehicle crime  \
0          59            0                      0            189   
1          58            0                      0            275   
2          29            0                      0            108   
3         136            0                      0            240   
4          54            0                      0            245   
...       ...          ...                    ...            ...   
5147       25           93                     27            155   
5148      109          172                    231            269   
5149       71          126                    127            243   
5150      102          155                     67            305   
5151      317          479                   2599            307   

      Violence and sexual offences  Violent crime  Month_Number  
0                                0            283            -3  
1                                0            337            -3  
2                                0            230            -3  
3                                0            492            -3  
4                                0            404            -3  
...              

In [18]:
merged_df.to_csv('crime_type_data.csv', index=False)

In [2]:
all_df = pd.read_csv(r"C:\Users\assis\Downloads\PAS+crime+extra_final.csv")
all_df

Q1  Q3C  Q3F  Q3G  Q3H  Q3I  Q3J  Q3K  Q3L  XQ3A  ...  \
0      2.0  4.0  4.0  5.0  NaN  2.0  NaN  2.0  1.0   NaN  ...   
1      5.0  1.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0   NaN  ...   
2      8.0  1.0  1.0  2.0  1.0  1.0  1.0  3.0  1.0   NaN  ...   
3      6.0  1.0  1.0  2.0  2.0  2.0  1.0  3.0  1.0   NaN  ...   
4      4.0  1.0  1.0  1.0  1.0  1.0  2.0  2.0  1.0   NaN  ...   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...   
75907  8.0  1.0  1.0  NaN  NaN  1.0  1.0  NaN  1.0   NaN  ...   
75908  6.0  2.0  2.0  NaN  NaN  2.0  1.0  NaN  2.0   NaN  ...   
75909  4.0  2.0  4.0  NaN  NaN  4.0  4.0  NaN  2.0   NaN  ...   
75910  7.0  2.0  2.0  NaN  NaN  2.0  2.0  NaN  2.0   NaN  ...   
75911  3.0  2.0  2.0  NaN  NaN  2.0  2.0  NaN  1.0   NaN  ...   

       Possession of weapons  Public disorder and weapons  Public order  \
0                          6                            0           148   
1                          3                            0            49   
2                          3                            0            49   
3                          3                            0            49   
4                          3                            0            49   
...                      ...                          ...           ...   
75907                     24                            0           181   
75908                      9                            0           193   
75909                     14                            0           197   
75910                     12                            0           170   
75911                     11                            0           117   

       Robbery  Shoplifting  Theft from the person  Vehicle crime  \
0           83          122                    448            225   
1           14           77                     13            105   
2           14           77                     13            105   
3           14           77                     13            105   
4           14           77                     13            105   
...        ...          ...                    ...            ...   
75907       73          108                     28            293   
75908       37           70                     38            365   
75909       79           77                     68            570   
75910       85           40                    197            257   
75911       35           97                     22            230   

       Violence and sexual offences  Violent crime  face-to-face  
0                               399              0             1  
1                               264              0             1  
2                               264              0             1  
3                               264              0             1  
4                               264              0             1  
...                             ...            ...           ...  
75907                           988              0             0  
75908                           738              0             0  
75909                           749              0             0  
75910                           622              0             0  
75911                           436              0             0  

[75912 rows x 671 columns]

In [4]:
new_df = all_df.copy()
new_df['Q60'] = new_df['Q60'].replace({1: 1, 2: 1, 3: 2, 4: 3, 5: 3})
new_df

Q1  Q3C  Q3F  Q3G  Q3H  Q3I  Q3J  Q3K  Q3L  XQ3A  ...  \
0      2.0  4.0  4.0  5.0  NaN  2.0  NaN  2.0  1.0   NaN  ...   
1      5.0  1.0  1.0  2.0  1.0  1.0  1.0  1.0  1.0   NaN  ...   
2      8.0  1.0  1.0  2.0  1.0  1.0  1.0  3.0  1.0   NaN  ...   
3      6.0  1.0  1.0  2.0  2.0  2.0  1.0  3.0  1.0   NaN  ...   
4      4.0  1.0  1.0  1.0  1.0  1.0  2.0  2.0  1.0   NaN  ...   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...   
75907  8.0  1.0  1.0  NaN  NaN  1.0  1.0  NaN  1.0   NaN  ...   
75908  6.0  2.0  2.0  NaN  NaN  2.0  1.0  NaN  2.0   NaN  ...   
75909  4.0  2.0  4.0  NaN  NaN  4.0  4.0  NaN  2.0   NaN  ...   
75910  7.0  2.0  2.0  NaN  NaN  2.0  2.0  NaN  2.0   NaN  ...   
75911  3.0  2.0  2.0  NaN  NaN  2.0  2.0  NaN  1.0   NaN  ...   

       Possession of weapons  Public disorder and weapons  Public order  \
0                          6                            0           148   
1                          3                            0            49   
2                          3                            0            49   
3                          3                            0            49   
4                          3                            0            49   
...                      ...                          ...           ...   
75907                     24                            0           181   
75908                      9                            0           193   
75909                     14                            0           197   
75910                     12                            0           170   
75911                     11                            0           117   

       Robbery  Shoplifting  Theft from the person  Vehicle crime  \
0           83          122                    448            225   
1           14           77                     13            105   
2           14           77                     13            105   
3           14           77                     13            105   
4           14           77                     13            105   
...        ...          ...                    ...            ...   
75907       73          108                     28            293   
75908       37           70                     38            365   
75909       79           77                     68            570   
75910       85           40                    197            257   
75911       35           97                     22            230   

       Violence and sexual offences  Violent crime  face-to-face  
0                               399              0             1  
1                               264              0             1  
2                               264              0             1  
3                               264              0             1  
4                               264              0             1  
...                             ...            ...           ...  
75907                           988              0             0  
75908                           738              0             0  
75909                           749              0             0  
75910                           622              0             0  
75911                           436              0             0  

[75912 rows x 671 columns]

In [5]:
top_20_conf = ['WT_Q63_B', 'SQ79DB', 'NQ135BDE', 'WT_Q58', 'XQ122A', 'NQCV28', 'Violence and sexual offences', 'XQ128A2B', 'WT_Q62', 'WT_Q64_B', 'NNQ27E', 'Q141', 'Borough', 'Vehicle crime', 'WT_Q44_E', 'NQCV7', 'Q62TI', 'WT_Q45_B', 'SQ132K', 'NQCV1', 'Q60']
top_20_trust = ['WT_Discrete', 'selfemployed_number', 'XQ122B', 'WT_Q45_B', 'WT_Q59', 'Vehicle crime', 'NQ57AA', 'White','Q62TG', 'WT_Q50_B', 'SQ109CAA', 'Monthly_pay_parttime', 'Monthly_pay_fulltime', 'Q1', 'WT_Q44_E', 'SQ132O', 'Q79H', 'WT_Q62', 'Q10F', 'PQ135AS', 'Q60']

In [11]:
confidence_df = new_df[top_20_conf]
trust_df = new_df[top_20_trust]
trust_df

WT_Discrete  selfemployed_number  XQ122B  WT_Q45_B  WT_Q59  \
0              NaN                20300     NaN       NaN     NaN   
1              NaN                17000     NaN       NaN     NaN   
2              NaN                17000     NaN       NaN     NaN   
3              NaN                17000     NaN       NaN     NaN   
4              NaN                17000     NaN       NaN     NaN   
...            ...                  ...     ...       ...     ...   
75907     1.631687                20700     3.0       NaN     NaN   
75908     4.035045                26300     2.0       NaN     NaN   
75909     0.582596                16100     2.0       NaN     NaN   
75910     2.134349                32000     1.0       NaN     NaN   
75911     1.632586                19300     2.0       NaN     NaN   

       Vehicle crime  NQ57AA     White  Q62TG  WT_Q50_B  ...  \
0                225     1.0  151000.0    2.0       NaN  ...   
1                105     1.0  152000.0    1.0       NaN  ...   
2                105     1.0  152000.0    1.0       NaN  ...   
3                105     3.0  152000.0    4.0       NaN  ...   
4                105     1.0  152000.0    2.0       NaN  ...   
...              ...     ...       ...    ...       ...  ...   
75907            293     NaN       NaN    1.0       NaN  ...   
75908            365     NaN       NaN    2.0       NaN  ...   
75909            570     NaN       NaN    2.0       NaN  ...   
75910            257     NaN       NaN    2.0       NaN  ...   
75911            230     NaN       NaN    2.0       NaN  ...   

       Monthly_pay_parttime  Monthly_pay_fulltime   Q1  WT_Q44_E  SQ132O  \
0                     712.4                2683.2  2.0  2.354809     NaN   
1                     772.4                2422.4  5.0  1.281054     NaN   
2                     772.4                2422.4  8.0  0.444971     NaN   
3                     772.4                2422.4  6.0  4.993085     NaN   
4                     772.4                2422.4  4.0  1.158942     NaN   
...                     ...                   ...  ...       ...     ...   
75907                 820.8                2842.8  8.0       NaN     NaN   
75908                 904.8                2714.4  6.0       NaN     NaN   
75909                 852.4                2682.0  4.0       NaN     NaN   
75910                 778.8                2813.2  7.0       NaN     NaN   
75911                 804.0                2826.4  3.0       NaN     NaN   

       Q79H  WT_Q62  Q10F  PQ135AS  Q60  
0       7.0     NaN   3.0      NaN  2.0  
1       7.0     NaN   3.0      NaN  1.0  
2       6.0     NaN   3.0      NaN  1.0  
3       5.0     NaN   3.0      NaN  2.0  
4       5.0     NaN   3.0      NaN  1.0  
...     ...     ...   ...      ...  ...  
75907   NaN     NaN   NaN      NaN  1.0  
75908   NaN     NaN   NaN      NaN  1.0  
75909   NaN     NaN   NaN      NaN  1.0  
75910   NaN     NaN   NaN      NaN  1.0  
75911   NaN     NaN   NaN      NaN  1.0  

[75912 rows x 21 columns]

In [12]:
trust_df = trust_df.dropna(subset=['Q60'])
trust_df

WT_Discrete  selfemployed_number  XQ122B  WT_Q45_B  WT_Q59  \
0              NaN                20300     NaN       NaN     NaN   
1              NaN                17000     NaN       NaN     NaN   
2              NaN                17000     NaN       NaN     NaN   
3              NaN                17000     NaN       NaN     NaN   
4              NaN                17000     NaN       NaN     NaN   
...            ...                  ...     ...       ...     ...   
75907     1.631687                20700     3.0       NaN     NaN   
75908     4.035045                26300     2.0       NaN     NaN   
75909     0.582596                16100     2.0       NaN     NaN   
75910     2.134349                32000     1.0       NaN     NaN   
75911     1.632586                19300     2.0       NaN     NaN   

       Vehicle crime  NQ57AA     White  Q62TG  WT_Q50_B  ...  \
0                225     1.0  151000.0    2.0       NaN  ...   
1                105     1.0  152000.0    1.0       NaN  ...   
2                105     1.0  152000.0    1.0       NaN  ...   
3                105     3.0  152000.0    4.0       NaN  ...   
4                105     1.0  152000.0    2.0       NaN  ...   
...              ...     ...       ...    ...       ...  ...   
75907            293     NaN       NaN    1.0       NaN  ...   
75908            365     NaN       NaN    2.0       NaN  ...   
75909            570     NaN       NaN    2.0       NaN  ...   
75910            257     NaN       NaN    2.0       NaN  ...   
75911            230     NaN       NaN    2.0       NaN  ...   

       Monthly_pay_parttime  Monthly_pay_fulltime   Q1  WT_Q44_E  SQ132O  \
0                     712.4                2683.2  2.0  2.354809     NaN   
1                     772.4                2422.4  5.0  1.281054     NaN   
2                     772.4                2422.4  8.0  0.444971     NaN   
3                     772.4                2422.4  6.0  4.993085     NaN   
4                     772.4                2422.4  4.0  1.158942     NaN   
...                     ...                   ...  ...       ...     ...   
75907                 820.8                2842.8  8.0       NaN     NaN   
75908                 904.8                2714.4  6.0       NaN     NaN   
75909                 852.4                2682.0  4.0       NaN     NaN   
75910                 778.8                2813.2  7.0       NaN     NaN   
75911                 804.0                2826.4  3.0       NaN     NaN   

       Q79H  WT_Q62  Q10F  PQ135AS  Q60  
0       7.0     NaN   3.0      NaN  2.0  
1       7.0     NaN   3.0      NaN  1.0  
2       6.0     NaN   3.0      NaN  1.0  
3       5.0     NaN   3.0      NaN  2.0  
4       5.0     NaN   3.0      NaN  1.0  
...     ...     ...   ...      ...  ...  
75907   NaN     NaN   NaN      NaN  1.0  
75908   NaN     NaN   NaN      NaN  1.0  
75909   NaN     NaN   NaN      NaN  1.0  
75910   NaN     NaN   NaN      NaN  1.0  
75911   NaN     NaN   NaN      NaN  1.0  

[73124 rows x 21 columns]

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import mean_squared_error
from sklearn.impute import SimpleImputer

X = trust_df.drop(columns=['Q60'])
y = trust_df['Q60']
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Impute missing values using Iterative Imputer
imputer = IterativeImputer()
X_imputed = imputer.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y, test_size=0.2, random_state=42)

C:\Users\assis\anaconda3\lib\site-packages\sklearn\impute\_iterative.py:800: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(


In [14]:
# Create LightGBM dataset
train_data = lgb.Dataset(X_train, label=y_train)
test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

# Set parameters
params = {
    'objective': 'multiclass',
    'num_class': 4,  # Update based on the number of categories
    'metric': 'multi_logloss',
    'boosting_type': 'gbdt',
    'learning_rate': 0.01,
    'num_leaves': 31,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': -1
}

# Train the model
gbm = lgb.train(params,
                train_data,
                num_boost_round=1000,
                valid_sets=[train_data, test_data],
                early_stopping_rounds=100)

C:\Users\assis\anaconda3\lib\site-packages\lightgbm\engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "


[1]	training's multi_logloss: 0.857373	valid_1's multi_logloss: 0.864207
Training until validation scores don't improve for 100 rounds
[2]	training's multi_logloss: 0.8537	valid_1's multi_logloss: 0.860703
[3]	training's multi_logloss: 0.850148	valid_1's multi_logloss: 0.857307
[4]	training's multi_logloss: 0.846731	valid_1's multi_logloss: 0.85405
[5]	training's multi_logloss: 0.84347	valid_1's multi_logloss: 0.850918
[6]	training's multi_logloss: 0.840329	valid_1's multi_logloss: 0.847936
[7]	training's multi_logloss: 0.837674	valid_1's multi_logloss: 0.845445
[8]	training's multi_logloss: 0.835067	valid_1's multi_logloss: 0.842975
[9]	training's multi_logloss: 0.832113	valid_1's multi_logloss: 0.840182
[10]	training's multi_logloss: 0.829597	valid_1's multi_logloss: 0.837778
[11]	training's multi_logloss: 0.826816	valid_1's multi_logloss: 0.835141
[12]	training's multi_logloss: 0.824127	valid_1's multi_logloss: 0.832592
[13]	training's multi_logloss: 0.821849	valid_1's multi_logloss

[114]	training's multi_logloss: 0.721258	valid_1's multi_logloss: 0.740788
[115]	training's multi_logloss: 0.72091	valid_1's multi_logloss: 0.740516
[116]	training's multi_logloss: 0.72054	valid_1's multi_logloss: 0.740252
[117]	training's multi_logloss: 0.720198	valid_1's multi_logloss: 0.739993
[118]	training's multi_logloss: 0.719844	valid_1's multi_logloss: 0.739737
[119]	training's multi_logloss: 0.719511	valid_1's multi_logloss: 0.739492
[120]	training's multi_logloss: 0.719166	valid_1's multi_logloss: 0.739252
[121]	training's multi_logloss: 0.718815	valid_1's multi_logloss: 0.738989
[122]	training's multi_logloss: 0.718471	valid_1's multi_logloss: 0.738728
[123]	training's multi_logloss: 0.71815	valid_1's multi_logloss: 0.738501
[124]	training's multi_logloss: 0.717816	valid_1's multi_logloss: 0.738253
[125]	training's multi_logloss: 0.717508	valid_1's multi_logloss: 0.738031
[126]	training's multi_logloss: 0.717199	valid_1's multi_logloss: 0.737806
[127]	training's multi_loglo

[224]	training's multi_logloss: 0.697212	valid_1's multi_logloss: 0.726734
[225]	training's multi_logloss: 0.697066	valid_1's multi_logloss: 0.726678
[226]	training's multi_logloss: 0.696925	valid_1's multi_logloss: 0.726619
[227]	training's multi_logloss: 0.696785	valid_1's multi_logloss: 0.726555
[228]	training's multi_logloss: 0.69664	valid_1's multi_logloss: 0.726509
[229]	training's multi_logloss: 0.696508	valid_1's multi_logloss: 0.726464
[230]	training's multi_logloss: 0.696374	valid_1's multi_logloss: 0.72642
[231]	training's multi_logloss: 0.696239	valid_1's multi_logloss: 0.726373
[232]	training's multi_logloss: 0.696103	valid_1's multi_logloss: 0.726321
[233]	training's multi_logloss: 0.695969	valid_1's multi_logloss: 0.726274
[234]	training's multi_logloss: 0.695842	valid_1's multi_logloss: 0.726223
[235]	training's multi_logloss: 0.695711	valid_1's multi_logloss: 0.726179
[236]	training's multi_logloss: 0.695572	valid_1's multi_logloss: 0.726137
[237]	training's multi_logl

[341]	training's multi_logloss: 0.683822	valid_1's multi_logloss: 0.722934
[342]	training's multi_logloss: 0.683728	valid_1's multi_logloss: 0.722922
[343]	training's multi_logloss: 0.683635	valid_1's multi_logloss: 0.722904
[344]	training's multi_logloss: 0.683538	valid_1's multi_logloss: 0.722874
[345]	training's multi_logloss: 0.683441	valid_1's multi_logloss: 0.722851
[346]	training's multi_logloss: 0.683348	valid_1's multi_logloss: 0.722835
[347]	training's multi_logloss: 0.683256	valid_1's multi_logloss: 0.722813
[348]	training's multi_logloss: 0.68316	valid_1's multi_logloss: 0.722791
[349]	training's multi_logloss: 0.683065	valid_1's multi_logloss: 0.722783
[350]	training's multi_logloss: 0.682962	valid_1's multi_logloss: 0.722764
[351]	training's multi_logloss: 0.682853	valid_1's multi_logloss: 0.722733
[352]	training's multi_logloss: 0.682753	valid_1's multi_logloss: 0.722703
[353]	training's multi_logloss: 0.682658	valid_1's multi_logloss: 0.722688
[354]	training's multi_log

[458]	training's multi_logloss: 0.673422	valid_1's multi_logloss: 0.72139
[459]	training's multi_logloss: 0.67334	valid_1's multi_logloss: 0.721378
[460]	training's multi_logloss: 0.673261	valid_1's multi_logloss: 0.721345
[461]	training's multi_logloss: 0.673172	valid_1's multi_logloss: 0.721326
[462]	training's multi_logloss: 0.673088	valid_1's multi_logloss: 0.721312
[463]	training's multi_logloss: 0.673012	valid_1's multi_logloss: 0.721306
[464]	training's multi_logloss: 0.672926	valid_1's multi_logloss: 0.721303
[465]	training's multi_logloss: 0.672845	valid_1's multi_logloss: 0.721282
[466]	training's multi_logloss: 0.672766	valid_1's multi_logloss: 0.721278
[467]	training's multi_logloss: 0.672692	valid_1's multi_logloss: 0.721274
[468]	training's multi_logloss: 0.672616	valid_1's multi_logloss: 0.721268
[469]	training's multi_logloss: 0.672546	valid_1's multi_logloss: 0.721263
[470]	training's multi_logloss: 0.672475	valid_1's multi_logloss: 0.721255
[471]	training's multi_logl

[569]	training's multi_logloss: 0.66493	valid_1's multi_logloss: 0.720885
[570]	training's multi_logloss: 0.664854	valid_1's multi_logloss: 0.720888
[571]	training's multi_logloss: 0.664784	valid_1's multi_logloss: 0.720907
[572]	training's multi_logloss: 0.664722	valid_1's multi_logloss: 0.720905
[573]	training's multi_logloss: 0.664659	valid_1's multi_logloss: 0.720918
[574]	training's multi_logloss: 0.664597	valid_1's multi_logloss: 0.720938
[575]	training's multi_logloss: 0.664541	valid_1's multi_logloss: 0.720949
[576]	training's multi_logloss: 0.664464	valid_1's multi_logloss: 0.720938
[577]	training's multi_logloss: 0.664389	valid_1's multi_logloss: 0.720931
[578]	training's multi_logloss: 0.664311	valid_1's multi_logloss: 0.720924
[579]	training's multi_logloss: 0.664235	valid_1's multi_logloss: 0.72091
[580]	training's multi_logloss: 0.664159	valid_1's multi_logloss: 0.720898
[581]	training's multi_logloss: 0.664086	valid_1's multi_logloss: 0.720885
[582]	training's multi_logl

[681]	training's multi_logloss: 0.65699	valid_1's multi_logloss: 0.720639
[682]	training's multi_logloss: 0.656927	valid_1's multi_logloss: 0.720641
[683]	training's multi_logloss: 0.656868	valid_1's multi_logloss: 0.720641
[684]	training's multi_logloss: 0.656807	valid_1's multi_logloss: 0.720647
[685]	training's multi_logloss: 0.65674	valid_1's multi_logloss: 0.720647
[686]	training's multi_logloss: 0.656673	valid_1's multi_logloss: 0.720645
[687]	training's multi_logloss: 0.656606	valid_1's multi_logloss: 0.720644
[688]	training's multi_logloss: 0.656541	valid_1's multi_logloss: 0.720644
[689]	training's multi_logloss: 0.656477	valid_1's multi_logloss: 0.720639
[690]	training's multi_logloss: 0.656417	valid_1's multi_logloss: 0.720632
[691]	training's multi_logloss: 0.656348	valid_1's multi_logloss: 0.720625
[692]	training's multi_logloss: 0.65628	valid_1's multi_logloss: 0.720626
[693]	training's multi_logloss: 0.656208	valid_1's multi_logloss: 0.720627
[694]	training's multi_loglo

In [15]:
set(trust_df['Q60'].to_list())

{1.0, 2.0, 3.0}

In [16]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
# Predict on test set
y_pred = gbm.predict(X_test, num_iteration=gbm.best_iteration)
y_pred_max = np.argmax(y_pred, axis=1)

print('Accuracy:', accuracy_score(y_test, y_pred_max))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_max)
print('Confusion Matrix:')
print(cm)

# Classification report
cr = classification_report(y_test, y_pred_max)
print('Classification Report:')
print(cr)

Accuracy: 0.6743931623931624
Confusion Matrix:
[[8420  708   97]
 [2805  998  226]
 [ 477  449  445]]
Classification Report:
              precision    recall  f1-score   support

         1.0       0.72      0.91      0.80      9225
         2.0       0.46      0.25      0.32      4029
         3.0       0.58      0.32      0.42      1371

    accuracy                           0.67     14625
   macro avg       0.59      0.50      0.51     14625
weighted avg       0.64      0.67      0.64     14625



In [59]:
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

y_train = y_train.astype(int)
y_test = y_test.astype(int)
y_train_encoded = y_train - 1
y_test_encoded = y_test - 1

classes = [1, 2, 3, 4, 5]

# Create and train the XGBoost model
xgb_model = XGBClassifier(eval_metric='mlogloss', use_label_encoder=True, classes=classes)
xgb_model.fit(X_train, y_train_encoded)
y_pred = xgb_model.predict(X_test)

print('Accuracy:', accuracy_score(y_test_encoded, y_pred))
print('Confusion Matrix:')
print(confusion_matrix(y_test_encoded, y_pred))
print('Classification Report:')
print(classification_report(y_test_encoded, y_pred))

C:\Users\assis\anaconda3\lib\site-packages\xgboost\core.py:160: UserWarning: [19:21:26] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\learner.cc:742: 
Parameters: { "classes" } are not used.

  warnings.warn(smsg, UserWarning)


Accuracy: 0.5693675213675213
Confusion Matrix:
[[ 115 1107   98    7    3]
 [ 131 6784  923   50    7]
 [  26 2596 1232  148   27]
 [   2  366  458  156   41]
 [   0   75  144   89   40]]
Classification Report:
              precision    recall  f1-score   support

           0       0.42      0.09      0.14      1330
           1       0.62      0.86      0.72      7895
           2       0.43      0.31      0.36      4029
           3       0.35      0.15      0.21      1023
           4       0.34      0.11      0.17       348

    accuracy                           0.57     14625
   macro avg       0.43      0.30      0.32     14625
weighted avg       0.52      0.57      0.52     14625



In [65]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from tqdm import tqdm

# Create and train the Random Forest model with a progress bar
rf_model = RandomForestClassifier(n_estimators=100)  # You can adjust the number of estimators
for _ in tqdm(range(100), desc='Training', unit='trees'):
    rf_model.fit(X_train, y_train)

# Predict and evaluate
y_pred = rf_model.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred))
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
print('Classification Report:')
print(classification_report(y_test, y_pred))

Training: 100%|████████████████████████████████████████████████████████| 100/100 [5:54:04<00:00, 212.44s/trees]


Accuracy: 0.5514529914529914
Confusion Matrix:
[[ 129 1071  119    7    4]
 [ 173 6519 1127   70    6]
 [  39 2570 1240  161   19]
 [   3  396  449  148   27]
 [   1   87  139   92   29]]
Classification Report:
              precision    recall  f1-score   support

           1       0.37      0.10      0.15      1330
           2       0.61      0.83      0.70      7895
           3       0.40      0.31      0.35      4029
           4       0.31      0.14      0.20      1023
           5       0.34      0.08      0.13       348

    accuracy                           0.55     14625
   macro avg       0.41      0.29      0.31     14625
weighted avg       0.51      0.55      0.51     14625

